[project]
name = "jeremyschroeder-net"
version = "0.0.5"
description = "My website code base"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.0",
    "requests>=2.32.4",
]
